export const FAILED = 'failed'
export const PASSED = 'passed'
export const MESSAGE_UZ = 'Noto`g`ri yuklangan ma`lumotlar tufayli ball hisoblanmadi.'
export const MESSAGE_RU = 'Из-за некорректно загруженных данных балл не засчитывался.'
export const MESSAGE_EN = 'Due to incorrectly uploaded data, the score was not counted.'